### ISSUE TITLE
Mac: Features(TIMESTAMP_QUERY) are required but not enabled on the device

### ISSUE THREAD

**Issue by utensil** [tracel-ai/cubecl#171]
On Github Actions runner `macos-latest`, a simple gelu example using CubeCL have just become resulting in the following error (and it was fine around 5 hours ago):

```
thread 'test_shader' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-22.1.0/src/backend/wgpu_core.rs:3411:5:
wgpu error: Validation Error

Caused by:
  In Device::create_query_set
    Features Features(TIMESTAMP_QUERY) are required but not enabled on the device
```

<details>
<summary>stack backtrace:</summary>

```
   0: rust_begin_unwind
             at /rustc/9322d183f45e0fd5a509820874cc5ff27744a479/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/9322d183f45e0fd5a509820874cc5ff27744a479/library/core/src/panicking.rs:74:14
   2: wgpu::backend::wgpu_core::default_error_handler
             at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-22.1.0/src/backend/wgpu_core.rs:3411:5
   3: core::ops::function::Fn::call
             at /rustc/9322d183f45e0fd5a509820874cc5ff27744a479/library/core/src/ops/function.rs:79:5
   4: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/9322d183f45e0fd5a509820874cc5ff27744a479/library/alloc/src/boxed.rs:2468:9
   5: wgpu::backend::wgpu_core::ErrorSinkRaw::handle_error
             at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-22.1.0/src/backend/wgpu_core.rs:3397:17
   6: wgpu::backend::wgpu_core::ContextWgpuCore::handle_error
             at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-22.1.0/src/backend/wgpu_core.rs:296:9
   7: wgpu::backend::wgpu_core::ContextWgpuCore::handle_error_nolabel
             at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-22.1.0/src/backend/wgpu_core.rs:308:9
   8: <wgpu::backend::wgpu_core::ContextWgpuCore as wgpu::context::Context>::device_create_query_set
             at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-22.1.0/src/backend/wgpu_core.rs:1410:13
   9: <T as wgpu::context::DynContext>::device_create_query_set
             at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-22.1.0/src/context.rs:2381:33
  10: wgpu::Device::create_query_set
             at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-22.1.0/src/lib.rs:3195:13
  11: cubecl_wgpu::compute::server::WgpuServer::new
             at /Users/runner/.cargo/git/checkouts/cubecl-aa41a28b39b598f9/e98de7c/crates/cubecl-wgpu/src/compute/server.rs:141:24
  12: cubecl_wgpu::runtime::create_client
             at /Users/runner/.cargo/git/checkouts/cubecl-aa41a28b39b598f9/e98de7c/crates/cubecl-wgpu/src/runtime.rs:144:18
  13: <cubecl_wgpu::runtime::WgpuRuntime as cubecl_core::runtime::Runtime>::client::{{closure}}
             at /Users/runner/.cargo/git/checkouts/cubecl-aa41a28b39b598f9/e98de7c/crates/cubecl-wgpu/src/runtime.rs:47:13
  14: cubecl_runtime::base::ComputeRuntime<Device,Server,Channel>::client
             at /Users/runner/.cargo/git/checkouts/cubecl-aa41a28b39b598f9/e98de7c/crates/cubecl-runtime/src/base.rs:55:42
  15: cubecl_xp::gelu_shader
             at ./src/lib.rs:26:18
  16: test_gelu::test_shader
             at ./tests/test_gelu.rs:29:16
  17: test_gelu::test_shader::{{closure}}
             at ./tests/test_gelu.rs:28:17
  18: core::ops::function::FnOnce::call_once
             at /rustc/9322d183f45e0fd5a509820874cc5ff27744a479/library/core/src/ops/function.rs:250:5
  19: core::ops::function::FnOnce::call_once
             at /rustc/9322d183f45e0fd5a509820874cc5ff27744a479/library/core/src/ops/function.rs:250:5
```

</details>

A likely cause is #167, which just [introduced such a query](https://github.com/tracel-ai/cubecl/pull/167/files#diff-9970d091b3bb24d553431cb5d25338ce7c2e4440de7fa7a102d8b2ca6b100391R70).

**Comment by ArthurBrussee** [comment]
Hmm strange... just to double check something - you're not creating your own wgpu device in any way? Do you happen to know what kind of hardware a macos-latest CI runner uses?

**Comment by utensil** [comment]
Thanks for the reply and the fix!

To answer the questions:

1. I didn't create my own wgpu device, just the same way as in the GELU example;
2. I don't know the specifics, my CI setup closely follows Burn's, so the same issue will hit downstream. I've tried both `macos-14` (i.e. `macos-latest`) and the deploying `macos-15`, no luck.

**Comment by utensil** [comment]
Locally on my MacBookPro M1 Sonoma 14.4.1, using commits after #167 , it works fine too. I can only guess that Github Actions default Mac is arm64 but not M-series (reserved for the paid runners), so it's possibly some early metal weirdness.

Actually, I was quite surprised it worked at all, because I thought default Github Actions runners has no GPU capacity until I saw Burn's CI setup (I also see that CubeCL's Mac CI is temporarily commented out).
